[package]
name = "sec-app"
version = "1.0.0"
description = "sec — локальный менеджер секретов"
authors = ["kaidstor"]
edition = "2021"

[lib]
name = "sec_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-window-state = "2"
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
